// --- TYPE DEFINITIONS ---
export interface Recipe {
  id: string;
  title: string;
  mealType: 'breakfast' | 'lunch' | 'snack' | 'dinner';
  servings: number;
  prepTimeMin: number;
  cookTimeMin: number;
  ingredients: string[];
  instructions: string[];
  tips_variation: string;
  source: string;
}

export interface DayPlan {
  breakfast: string; // recipeId
  lunch: string;     // recipeId
  snack: string;     // recipeId
  dinner: string;    // recipeId
}

// Version identifier for the current recipe dataset
export const recipeDataVersion = 'v10-ebook-dinners-20240727';

// --- RECIPE DATABASE ---
export const recipes: { [id: string]: Recipe } = {
  // --- Breakfasts ---
  'avocado-toast-whole-grain': {
    id: 'avocado-toast-whole-grain',
    title: 'Avocado Toast with Whole-Grain Bread',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 2,
    ingredients: ['1 slice whole-grain bread', '1/2 avocado, mashed', '1 tsp lemon juice', 'Pinch of black pepper'],
    instructions: ['Toast the bread until golden brown.', 'Mash the avocado with lemon juice and spread it over the toast.', 'Season with black pepper and serve.'],
    tips_variation: 'Add sliced tomatoes or a poached egg for extra protein and flavor.',
    source: 'THE DASH DIET AFTER 50',
  },
  'banana-butter-rice-cakes': {
    id: 'banana-butter-rice-cakes',
    title: 'Banana Butter Rice Cakes',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1 rice cake', '1 tbsp natural peanut butter', '1/2 banana, sliced'],
    instructions: ['Spread peanut butter over the rice cake.', 'Top with banana slices and serve.'],
    tips_variation: 'Swap peanut butter for almond or sunflower seed butter for a different taste.',
    source: 'THE DASH DIET AFTER 50',
  },
  'greek-yogurt-honey-nuts': {
    id: 'greek-yogurt-honey-nuts',
    title: 'Greek Yogurt with Honey & Nuts',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1 cup low-fat Greek yogurt', '1 tsp honey', '1 tbsp chopped walnuts'],
    instructions: ['Mix yogurt with honey.', 'Sprinkle chopped walnuts on top and enjoy.'],
    tips_variation: 'Use almonds or pecans instead of walnuts.',
    source: 'THE DASH DIET AFTER 50',
  },
  'cottage-cheese-fresh-berries': {
    id: 'cottage-cheese-fresh-berries',
    title: 'Cottage Cheese with Fresh Berries',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1/2 cup low-fat cottage cheese', '1/2 cup mixed berries (strawberries, blueberries, raspberries)'],
    instructions: ['Combine cottage cheese with fresh berries.', 'Stir gently and serve.'],
    tips_variation: 'Sprinkle with cinnamon or flaxseed for added flavor.',
    source: 'THE DASH DIET AFTER 50',
  },
  'spinach-almond-milk-smoothie': {
    id: 'spinach-almond-milk-smoothie',
    title: 'Spinach & Almond Milk Smoothie',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1 cup unsweetened almond milk', '1/2 cup fresh spinach', '1/2 banana', '1 tbsp chia seeds'],
    instructions: ['Blend all ingredients until smooth.', 'Serve immediately.'],
    tips_variation: 'Add a teaspoon of honey or swap chia seeds for flaxseeds.',
    source: 'THE DASH DIET AFTER 50',
  },
  'english-muffin-almond-butter': {
    id: 'english-muffin-almond-butter',
    title: 'Whole-Wheat English Muffin with Almond Butter',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1 whole-wheat English muffin', '1 tbsp almond butter'],
    instructions: ['Toast the English muffin.', 'Spread with almond butter and serve.'],
    tips_variation: 'Add sliced bananas or honey for extra flavor.',
    source: 'THE DASH DIET AFTER 50',
  },
  'hard-boiled-eggs-tomatoes': {
    id: 'hard-boiled-eggs-tomatoes',
    title: 'Hard-Boiled Eggs with Cherry Tomatoes',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 10,
    cookTimeMin: 0,
    ingredients: ['2 hard-boiled eggs', '1/2 cup cherry tomatoes'],
    instructions: ['Slice the eggs and serve with cherry tomatoes.', 'Sprinkle with black pepper or a drizzle of olive oil.'],
    tips_variation: 'Add fresh basil or a sprinkle of feta cheese.',
    source: 'THE DASH DIET AFTER 50',
  },
  'instant-oatmeal-flaxseed': {
    id: 'instant-oatmeal-flaxseed',
    title: 'Instant Oatmeal with Flaxseed',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1/2 cup instant oats', '1 cup hot water', '1 tbsp flaxseeds', '1 tsp honey (optional)'],
    instructions: ['Mix oats with hot water.', 'Stir in flaxseeds and drizzle with honey if desired.'],
    tips_variation: 'Add cinnamon or chopped nuts for extra texture.',
    source: 'THE DASH DIET AFTER 50',
  },
  'scrambled-tofu-peppers': {
    id: 'scrambled-tofu-peppers',
    title: 'Scrambled Tofu with Bell Peppers and Onions',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 10,
    cookTimeMin: 5,
    ingredients: ['1/2 cup firm tofu, crumbled', '1/4 cup bell peppers, chopped', '1/4 cup onions, chopped', '1 tsp olive oil', 'Pinch of turmeric', 'Black pepper to taste'],
    instructions: ['Heat olive oil in a pan over medium heat.', 'Sauté onions and bell peppers until soft.', 'Add crumbled tofu, turmeric, and black pepper.', 'Cook for 3-5 minutes and serve hot.'],
    tips_variation: 'Add spinach or mushrooms for extra nutrients.',
    source: 'THE DASH DIET AFTER 50',
  },
  'egg-spinach-breakfast-wrap': {
    id: 'egg-spinach-breakfast-wrap',
    title: 'Egg and Spinach Breakfast Wrap',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 10,
    cookTimeMin: 5,
    ingredients: ['2 eggs', '1/2 cup spinach', '1 whole-wheat tortilla', '1 tsp olive oil'],
    instructions: ['Scramble eggs with spinach in olive oil over medium heat.', 'Wrap the mixture in a whole-wheat tortilla and serve.'],
    tips_variation: 'Add feta cheese or avocado for extra flavor.',
    source: 'THE DASH DIET AFTER 50',
  },
  'salmon-avocado-bagel': {
    id: 'salmon-avocado-bagel',
    title: 'Salmon and Avocado Whole-Grain Bagel',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 2,
    ingredients: ['1 whole-grain bagel', '2 oz smoked salmon', '1/2 avocado, sliced', '1 tsp lemon juice'],
    instructions: ['Toast the bagel.', 'Spread avocado on bagel halves.', 'Top with smoked salmon and drizzle with lemon juice.'],
    tips_variation: 'Use low-fat cream cheese instead of avocado for a different texture.',
    source: 'THE DASH DIET AFTER 50',
  },
   'quinoa-black-bean-bowl': {
    id: 'quinoa-black-bean-bowl',
    title: 'Quinoa and Black Bean Breakfast Bowl',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 10,
    cookTimeMin: 0,
    ingredients: ['1/2 cup cooked quinoa', '1/4 cup black beans', '1/4 cup cherry tomatoes', '1 tsp olive oil'],
    instructions: ['Mix all ingredients together and serve warm or cold.'],
    tips_variation: 'Add avocado or a boiled egg for extra protein.',
    source: 'THE DASH DIET AFTER 50',
  },
  'lentil-spinach-scramble': {
    id: 'lentil-spinach-scramble',
    title: 'Lentil and Spinach Scramble',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 10,
    cookTimeMin: 5,
    ingredients: ['1/2 cup cooked lentils', '1/2 cup spinach', '2 egg whites', '1 tsp olive oil'],
    instructions: ['Sauté spinach in olive oil over medium heat.', 'Add lentils and egg whites, cooking until eggs are set.'],
    tips_variation: 'Use kale instead of spinach.',
    source: 'THE DASH DIET AFTER 50',
  },
  'baked-oatmeal-cinnamon-apples': {
    id: 'baked-oatmeal-cinnamon-apples',
    title: 'Baked Oatmeal with Cinnamon and Apples',
    mealType: 'breakfast',
    servings: 2,
    prepTimeMin: 5,
    cookTimeMin: 25,
    ingredients: ['1/2 cup rolled oats', '1/2 cup unsweetened almond milk', '1 small apple, diced', '1 tbsp maple syrup or honey', '1/2 tsp ground cinnamon', '1/4 tsp baking powder'],
    instructions: ['Preheat oven to 350°F (175°C).', 'In a bowl, mix all ingredients.', 'Pour mixture into a small baking dish and bake for 20-25 minutes until golden.'],
    tips_variation: 'Swap apples for pears or bananas.',
    source: 'THE DASH DIET AFTER 50',
  },
  'muesli-almonds-dried-fruits': {
    id: 'muesli-almonds-dried-fruits',
    title: 'Muesli with Almonds and Dried Fruits',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1/2 cup rolled oats', '1 tbsp almonds', '1 tbsp dried cranberries', '1 cup low-fat milk'],
    instructions: ['Mix all ingredients in a bowl.', 'Let sit for 5 minutes before eating.'],
    tips_variation: 'Use coconut flakes or chia seeds for extra nutrients.',
    source: 'THE DASH DIET AFTER 50',
  },
  'chia-pudding-berries-coconut': {
    id: 'chia-pudding-berries-coconut',
    title: 'Chia Pudding with Berries and Coconut Milk',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['2 tbsp chia seeds', '1 cup coconut milk', '1/2 cup mixed berries'],
    instructions: ['Mix chia seeds with coconut milk in a bowl.', 'Refrigerate overnight.', 'Top with mixed berries before serving.'],
    tips_variation: 'Use almond milk instead of coconut milk for a lighter version.',
    source: 'THE DASH DIET AFTER 50',
  },
  'flaxseed-pancakes-blueberries': {
    id: 'flaxseed-pancakes-blueberries',
    title: 'Flaxseed Pancakes with Blueberries',
    mealType: 'breakfast',
    servings: 2,
    prepTimeMin: 5,
    cookTimeMin: 10,
    ingredients: ['1/2 cup whole wheat flour', '1 tbsp flaxseeds', '1/2 tsp baking powder', '1 egg', '1/2 cup almond milk', '1/4 cup blueberries'],
    instructions: ['Mix ingredients in a bowl.', 'Cook pancakes on a skillet over medium heat until golden brown.'],
    tips_variation: 'Substitute blueberries with chopped nuts.',
    source: 'THE DASH DIET AFTER 50',
  },
  'toast-hummus-avocado': {
    id: 'toast-hummus-avocado',
    title: 'Whole-Grain Toast with Hummus and Avocado',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 2,
    ingredients: ['1 slice whole-grain bread', '2 tbsp hummus', '1/2 avocado, sliced'],
    instructions: ['Toast the bread.', 'Spread hummus on toast.', 'Top with avocado slices and serve.'],
    tips_variation: 'Sprinkle sesame seeds for extra texture.',
    source: 'THE DASH DIET AFTER 50',
  },
  'overnight-oats-walnuts-raisins': {
    id: 'overnight-oats-walnuts-raisins',
    title: 'Overnight Oats with Walnuts and Raisins',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1/2 cup rolled oats', '1 cup almond milk', '1 tbsp walnuts', '1 tbsp raisins'],
    instructions: ['Mix all ingredients in a bowl.', 'Refrigerate overnight and serve cold.'],
    tips_variation: 'Add a teaspoon of honey for extra sweetness.',
    source: 'THE DASH DIET AFTER 50',
  },
  'smoothie-bowl-mixed-seeds': {
    id: 'smoothie-bowl-mixed-seeds',
    title: 'Smoothie Bowl with Mixed Seeds',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 5,
    cookTimeMin: 0,
    ingredients: ['1 banana', '1/2 cup spinach', '1 cup almond milk', '1 tbsp mixed seeds (chia, flax, sunflower)'],
    instructions: ['Blend all ingredients until smooth.', 'Pour into a bowl and top with seeds.'],
    tips_variation: 'Add granola for extra crunch.',
    source: 'THE DASH DIET AFTER 50',
  },
  'buckwheat-porridge-almond-butter': {
    id: 'buckwheat-porridge-almond-butter',
    title: 'Buckwheat Porridge with Almond Butter',
    mealType: 'breakfast',
    servings: 1,
    prepTimeMin: 2,
    cookTimeMin: 8,
    ingredients: ['1/2 cup buckwheat groats', '1 cup water', '1 tbsp almond butter'],
    instructions: ['Cook buckwheat in water until soft.', 'Stir in almond butter and serve.'],
    tips_variation: 'Add cinnamon or nutmeg for extra flavor.',
    source: 'THE DASH DIET AFTER 50',
  },
  'egg-frittata-whole-grain-toast': {
    id: 'egg-frittata-whole-grain-toast',
    title: 'Egg and Vegetable Frittata with Whole-Grain Toast',
    mealType: 'breakfast',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 12,
    ingredients: ['4 large eggs', '1/2 cup baby spinach', '1/2 cup cherry tomatoes, halved', '2 slices whole-grain bread'],
    instructions: ['Preheat broiler.', 'In a bowl, whisk eggs and milk. Sauté vegetables in an oven-safe skillet.', 'Pour eggs over vegetables and cook until edges are set.', 'Sprinkle with cheese and broil until puffed and golden.', 'Serve with toast.'],
    tips_variation: 'Use any leftover cooked vegetables. Substitute Swiss cheese with low-fat cheddar or mozzarella.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'maple-glazed-acorn-squash': {
    id: 'maple-glazed-acorn-squash',
    title: 'Maple-Glazed Acorn Squash for Two',
    mealType: 'breakfast',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 35,
    ingredients: ['1 small acorn squash (about 1.5 lbs)', '1 tbsp pure maple syrup', '1 tbsp extra-virgin olive oil', '1/2 tsp ground cinnamon'],
    instructions: ['Preheat oven to 400°F. Slice squash into wedges.', 'Whisk maple syrup, olive oil, and cinnamon.', 'Brush glaze over squash wedges.', 'Roast for 30-35 minutes until tender and golden.'],
    tips_variation: 'Swap acorn squash for delicata or butternut squash. Add a sprinkle of toasted pumpkin seeds.',
    source: 'DASH Over 50 - Holiday Reset Edition',
  },
  'baked-apples-oat-pecan-crumble': {
    id: 'baked-apples-oat-pecan-crumble',
    title: 'Baked Apples with Oat-Pecan Crumble',
    mealType: 'breakfast',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 35,
    ingredients: ['2 medium apples (Honeycrisp or Gala)', '2 tbsp rolled oats', '1 tbsp chopped pecans', '1 tbsp maple syrup'],
    instructions: ['Preheat oven to 375°F. Core the apples.', 'Combine oats, pecans, and maple syrup to make the crumble.', 'Stuff the apples with the crumble mixture.', 'Bake for 25-35 minutes until tender.'],
    tips_variation: 'Swap pecans for walnuts or almonds. Add dried cranberries or raisins to the crumble.',
    source: 'DASH Over 50 - Holiday Reset Edition',
  },
   'spiced-pumpkin-buddha-bowl': {
    id: 'spiced-pumpkin-buddha-bowl',
    title: 'Spiced Pumpkin and Chickpea Buddha Bowl',
    mealType: 'breakfast',
    servings: 2,
    prepTimeMin: 12,
    cookTimeMin: 15,
    ingredients: ['2 cups cubed pumpkin', '1 can (15-ounce) chickpeas, rinsed', '1 cup cooked brown rice', '2 cups baby spinach leaves', '1/4 cup plain nonfat Greek yogurt', '1 tbsp tahini'],
    instructions: ['Preheat air fryer to 400°F. Toss pumpkin with spices and air fry for 12-14 minutes.', 'Add chickpeas to the air fryer for the last 2 minutes.', 'Wilt spinach in the microwave.', 'Whisk yogurt and tahini for dressing.', 'Assemble bowls with rice, spinach, pumpkin, chickpeas, and dressing.'],
    tips_variation: 'Use butternut squash instead of pumpkin. Swap brown rice for quinoa or farro.',
    source: 'Cookbook DASH Diet for Couples',
  },
  // --- Lunches ---
  'lemon-tahini-chickpea-salad-bowl': {
    id: 'lemon-tahini-chickpea-salad-bowl',
    title: 'Lemon-Tahini Chickpea Salad Bowl',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 0,
    ingredients: ['1 can (15-ounce) chickpeas, rinsed', '1 cup cherry tomatoes, halved', '1 cup cucumber, diced', '1 cup broccoli florets, steamed', '2 tbsp tahini', '2 tbsp fresh lemon juice'],
    instructions: ['Whisk tahini and lemon juice for dressing.', 'Combine chickpeas, tomatoes, cucumber, and broccoli.', 'Toss with dressing and serve over mixed greens.'],
    tips_variation: 'Substitute white beans for chickpeas. Replace tahini with unsweetened plain Greek yogurt.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'avocado-white-bean-sandwich': {
    id: 'avocado-white-bean-sandwich',
    title: 'Avocado and White Bean Open-Faced Sandwich',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 0,
    ingredients: ['1 can (15-ounce) cannellini beans, rinsed', '1 ripe avocado', '2 slices whole-grain bread, toasted', '4 slices ripe tomato'],
    instructions: ['Mash beans and avocado together.', 'Spread on toasted bread.', 'Top with arugula, tomato slices, and red onion.'],
    tips_variation: 'Use mashed edamame or chickpeas instead of white beans. Swap tomato for cucumber.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'grilled-vegetable-pesto-farro-bowl': {
    id: 'grilled-vegetable-pesto-farro-bowl',
    title: 'Grilled Vegetable and Pesto Farro Bowl',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 20,
    ingredients: ['1/2 cup uncooked farro', '1 small zucchini', '1 small red bell pepper', '1/2 cup no-salt-added canned chickpeas', '2 tbsp low-sodium basil pesto'],
    instructions: ['Cook farro according to package directions.', 'Grill or air fry chopped vegetables until tender.', 'Toss chickpeas with 1 tbsp pesto.', 'Assemble bowls with farro, spinach, grilled vegetables, and pesto chickpeas.'],
    tips_variation: 'Substitute brown rice or quinoa for farro. Use homemade pesto with walnuts for a nut-free option.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'turkey-apple-arugula-panini': {
    id: 'turkey-apple-arugula-panini',
    title: 'Turkey, Apple and Arugula Whole-Wheat Panini',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 6,
    ingredients: ['4 slices whole-wheat sandwich bread', '4 ounces low-sodium sliced turkey breast', '1 small crisp apple, thinly sliced', '1/2 cup baby arugula', '2 tbsp part-skim ricotta cheese'],
    instructions: ['Spread ricotta mixture on bread.', 'Layer turkey, apple slices, and arugula.', 'Cook in a panini press for 5-6 minutes until golden and crisp.'],
    tips_variation: 'Use pear slices instead of apple. Replace ricotta with low-fat cream cheese or goat cheese.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'roasted-beet-orange-goat-cheese-salad': {
    id: 'roasted-beet-orange-goat-cheese-salad',
    title: 'Roasted Beet, Orange and Goat Cheese Salad',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 30,
    ingredients: ['2 small beets', '1 medium navel orange', '2 ounces goat cheese, crumbled', '4 cups mixed baby greens', '2 tbsp unsalted pistachios'],
    instructions: ['Roast beets until tender, then peel and dice.', 'Assemble salad with greens, orange slices, roasted beets, and goat cheese.', 'Drizzle with a simple balsamic vinaigrette and top with pistachios.'],
    tips_variation: 'Substitute feta for goat cheese. Use walnuts or almonds instead of pistachios.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'warm-barley-mushroom-pilaf-spinach': {
    id: 'warm-barley-mushroom-pilaf-spinach',
    title: 'Warm Barley and Mushroom Pilaf with Spinach',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 25,
    ingredients: ['1/2 cup pearled barley', '1.5 cups low-sodium vegetable broth', '6 ounces cremini mushrooms, sliced', '3 cups baby spinach'],
    instructions: ['Cook barley in broth until tender.', 'Sauté mushrooms until browned.', 'Stir in cooked barley and spinach until wilted.', 'Finish with fresh parsley and lemon juice.'],
    tips_variation: 'Substitute farro or brown rice for barley. Use baby kale or Swiss chard instead of spinach.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'smoky-paprika-tofu-lettuce-wraps': {
    id: 'smoky-paprika-tofu-lettuce-wraps',
    title: 'Smoky Paprika Tofu Lettuce Wraps',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 10,
    ingredients: ['8 ounces extra-firm tofu, pressed and cubed', '1 tbsp olive oil', '1 tsp smoked paprika', '8 large butter lettuce leaves', '1/2 cup shredded carrots', '1/2 avocado, sliced'],
    instructions: ['Toss tofu with olive oil and spices.', 'Air fry at 375°F for 10 minutes until golden and crisp.', 'Assemble wraps with lettuce, carrots, bell pepper, avocado, and tofu.'],
    tips_variation: 'Use tempeh or cooked chickpeas instead of tofu. Swap Greek yogurt for a dairy-free yogurt.',
    source: 'Cookbook DASH Diet for Couples',
  },
   'tuna-white-bean-nicoise-salad': {
    id: 'tuna-white-bean-nicoise-salad',
    title: 'Tuna and White Bean Niçoise Salad',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 0,
    ingredients: ['1 can (5-ounce) no-salt-added tuna', '1 cup no-salt-added canned white beans', '2 cups mixed baby greens', '1/2 cup steamed green beans', '1 hard-boiled egg, quartered'],
    instructions: ['Arrange greens, tomatoes, green beans, radishes, and olives on plates.', 'Top with tuna and white beans.', 'Add egg quarters and drizzle with a simple vinaigrette.'],
    tips_variation: 'Use canned salmon or cooked chicken instead of tuna. Substitute garbanzo beans for white beans.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'curried-lentil-carrot-stew': {
    id: 'curried-lentil-carrot-stew',
    title: 'Curried Lentil and Carrot Stew with Brown Rice',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 25,
    ingredients: ['1/2 cup dry brown rice', '1/2 cup dry brown lentils', '2 medium carrots, diced', '1 tbsp salt-free curry powder', '1 can (14.5-ounce) no-salt-added diced tomatoes'],
    instructions: ['Cook brown rice.', 'In a saucepan, sauté onion and carrots, then add garlic and spices.', 'Add lentils, tomatoes, and broth. Simmer for 20-25 minutes until lentils are tender.', 'Serve stew over brown rice.'],
    tips_variation: 'Use red lentils for a creamier texture. Substitute sweet potatoes for carrots.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'caprese-chickpea-salad': {
    id: 'caprese-chickpea-salad',
    title: 'Caprese Chickpea Salad with Balsamic Reduction',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 5,
    ingredients: ['1 can (15-ounce) chickpeas, rinsed', '1 cup cherry tomatoes, halved', '1/2 cup fresh mozzarella balls (ciliegine)', '1/4 cup fresh basil leaves, torn', '1 tbsp balsamic vinegar', '1 tsp honey'],
    instructions: ['Simmer balsamic vinegar and honey until reduced by half.', 'Combine chickpeas, tomatoes, mozzarella, and basil.', 'Drizzle with olive oil, black pepper, and the balsamic reduction.'],
    tips_variation: 'Use canned white beans or edamame instead of chickpeas. Replace mozzarella with diced avocado.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'turkey-avocado-wrap-cilantro-yogurt': {
    id: 'turkey-avocado-wrap-cilantro-yogurt',
    title: 'Turkey Avocado Wrap with Cilantro-Yogurt Sauce',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 0,
    ingredients: ['4 ounces low-sodium sliced turkey breast', '2 (8-inch) whole wheat tortillas', '1/2 ripe avocado, sliced', '1/4 cup plain nonfat Greek yogurt', '2 tbsp chopped fresh cilantro'],
    instructions: ['Combine yogurt, cilantro, lime juice, and spices for the sauce.', 'Spread sauce on tortillas.', 'Layer turkey, avocado, spinach, carrots, and bell pepper.', 'Roll up tightly and serve.'],
    tips_variation: 'Use low-sodium chicken breast or tofu slices instead of turkey. Swap cilantro for parsley or chives.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'zesty-shrimp-bowl-cauliflower-rice': {
    id: 'zesty-shrimp-bowl-cauliflower-rice',
    title: 'Zesty Cilantro Lime Shrimp Bowl with Cauliflower Rice',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 10,
    ingredients: ['8 ounces raw large shrimp, peeled', '2 cups cauliflower rice', '1/2 cup diced red bell pepper', '1/2 cup diced cucumber', '1/2 ripe avocado, diced', '2 tbsp plain nonfat Greek yogurt'],
    instructions: ['Toss shrimp with spices and air fry or pan-sear until cooked.', 'Microwave cauliflower rice.', 'Whisk yogurt with lime juice and cilantro for the sauce.', 'Assemble bowls with cauliflower rice, shrimp, and fresh vegetables. Drizzle with sauce.'],
    tips_variation: 'Use cooked chicken or tofu cubes instead of shrimp. Swap cauliflower rice for brown rice or quinoa.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'sweet-potato-black-bean-quesadilla': {
    id: 'sweet-potato-black-bean-quesadilla',
    title: 'Roasted Sweet Potato and Black Bean Quesadilla',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 10,
    ingredients: ['1 medium sweet potato, diced and roasted', '1/2 cup no-salt-added black beans', '2 (8-inch) whole-wheat tortillas', '1/2 cup shredded reduced-fat cheddar cheese'],
    instructions: ['Mash half the black beans and mix with whole beans, roasted sweet potato, onion, and cilantro.', 'Sprinkle cheese on one half of each tortilla, top with bean mixture, then more cheese.', 'Fold and cook in a nonstick skillet until golden brown and cheese is melted.'],
    tips_variation: 'Use butternut squash or pumpkin instead of sweet potato. Replace black beans with pinto or kidney beans.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'grilled-pear-walnut-gorgonzola-salad': {
    id: 'grilled-pear-walnut-gorgonzola-salad',
    title: 'Grilled Pear, Walnut and Gorgonzola Salad',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 8,
    ingredients: ['2 ripe but firm pears, quartered', '4 cups mixed baby greens', '1/4 cup crumbled Gorgonzola cheese', '1/4 cup walnut halves, toasted', '1 tbsp honey', '1 tbsp Dijon mustard'],
    instructions: ['Grill pear quarters until grill marks appear.', 'Whisk together honey, mustard, and vinegar for the dressing.', 'Assemble salad with greens, red onion, walnuts, and cranberries.', 'Top with sliced grilled pears and drizzle with dressing.'],
    tips_variation: 'Use blue cheese or reduced-fat feta instead of Gorgonzola. Substitute pecans or almonds for walnuts.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'miso-scallion-soba-bowl': {
    id: 'miso-scallion-soba-bowl',
    title: 'Miso-Scallion Soba Bowl with Steamed Greens',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 12,
    ingredients: ['4 ounces dry buckwheat soba noodles', '3 cups low-sodium vegetable broth', '1 tbsp white miso paste', '2 cups baby bok choy', '1/2 cup shelled edamame'],
    instructions: ['Cook soba noodles. Whisk miso into warm broth.', 'Steam bok choy and broccoli in the microwave.', 'Divide noodles into bowls, arrange vegetables, and ladle hot miso broth over top.'],
    tips_variation: 'Use whole-wheat spaghetti if soba is unavailable. Swap baby spinach or Swiss chard for bok choy.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'greek-lentil-salad-cucumbers-feta': {
    id: 'greek-lentil-salad-cucumbers-feta',
    title: 'Greek Lentil Salad with Cucumbers and Feta',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 12,
    cookTimeMin: 18,
    ingredients: ['1/2 cup dry brown or green lentils', '1/2 cup diced English cucumber', '1/2 cup cherry tomatoes, quartered', '1/4 cup crumbled reduced-fat feta cheese', '1 tbsp red wine vinegar'],
    instructions: ['Cook lentils until tender but not mushy; cool.', 'Steam green beans in the microwave until crisp-tender.', 'Combine lentils, green beans, cucumber, tomatoes, and onion.', 'Whisk dressing and toss with salad. Fold in feta and parsley.'],
    tips_variation: 'Use canned, no-salt-added lentils for faster prep. Swap reduced-fat goat cheese for feta.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'herbed-lentil-salad-lettuce-cups': {
    id: 'herbed-lentil-salad-lettuce-cups',
    title: 'Herbed Lentil Salad Lettuce Cups',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 20,
    ingredients: ['1 cup dried green or brown lentils', '1/2 cup finely diced red bell pepper', '2 tbsp finely chopped fresh parsley', '2 tbsp finely chopped fresh dill', '12 large crisp lettuce leaves'],
    instructions: ['Cook lentils with a bay leaf until tender; cool.', 'Whisk together olive oil, lemon juice, vinegar, mustard, and pepper for dressing.', 'Combine lentils with vegetables and herbs, toss with dressing.', 'Spoon lentil salad into lettuce cups to serve.'],
    tips_variation: 'Substitute cooked French lentils for a firmer texture. Swap parsley or dill for fresh cilantro or basil.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'heirloom-tomato-white-bean-bruschetta': {
    id: 'heirloom-tomato-white-bean-bruschetta',
    title: 'Heirloom Tomato, Basil and White Bean Bruschetta',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 5,
    ingredients: ['1 cup canned no-salt-added cannellini beans', '1 cup diced heirloom tomatoes', '2 tbsp finely chopped fresh basil', '4 slices multigrain bread'],
    instructions: ['Lightly mash cannellini beans.', 'Gently toss with tomatoes, basil, olive oil, and balsamic vinegar.', 'Toast multigrain bread.', 'Spoon bean and tomato mixture over toasted bread.'],
    tips_variation: 'Use navy beans or great northern beans instead of cannellini. Add a few baby arugula leaves on top.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'warm-farro-salad-roasted-vegetables': {
    id: 'warm-farro-salad-roasted-vegetables',
    title: 'Warm Farro Salad with Roasted Vegetables and Walnuts',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 25,
    ingredients: ['1/2 cup uncooked farro', '1 small red bell pepper', '1 small zucchini', '1/4 cup chopped walnuts, toasted', '2 cups baby spinach'],
    instructions: ['Cook farro. Roast chopped vegetables until tender.', 'Toast walnuts in a dry skillet.', 'Whisk together balsamic vinegar, Dijon mustard, and honey for dressing.', 'Combine cooked farro, roasted vegetables, walnuts, and parsley. Drizzle with dressing and toss.', 'Add baby spinach and toss again until just wilted.'],
    tips_variation: 'Substitute barley or brown rice for farro. Use pecans or slivered almonds instead of walnuts.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'warm-lentil-walnut-stuffed-pears': {
    id: 'warm-lentil-walnut-stuffed-pears',
    title: 'Warm Lentil and Walnut Stuffed Pears',
    mealType: 'lunch',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 30,
    ingredients: ['2 ripe but firm Bosc or Anjou pears', '1/2 cup cooked brown or green lentils', '1/4 cup finely chopped walnuts', '1 tbsp dried cranberries, chopped', '1 tbsp balsamic vinegar'],
    instructions: ['Preheat oven to 375°F. Halve and core pears.', 'Sauté shallot and celery, then add lentils, walnuts, and thyme.', 'Stir in parsley, cranberries, balsamic vinegar, and honey.', 'Spoon the lentil-walnut mixture into the pears.', 'Bake for 20 minutes covered, then 8-10 minutes uncovered.'],
    tips_variation: 'Swap walnuts for pecans or almonds. Use golden raisins instead of cranberries.',
    source: 'DASH Over 50 - Holiday Reset Edition',
  },
  // --- Snacks ---
  'cranberry-herb-goat-cheese-crostini': {
    id: 'cranberry-herb-goat-cheese-crostini',
    title: 'Cranberry-Herb Goat Cheese Crostini',
    mealType: 'snack',
    servings: 10,
    prepTimeMin: 10,
    cookTimeMin: 10,
    ingredients: ['1 whole-wheat baguette', '6 ounces low-sodium goat cheese', '1/4 cup dried cranberries, chopped', '2 tbsp unsalted roasted pistachios, chopped'],
    instructions: ['Slice baguette and toast rounds until golden.', 'Combine goat cheese, cranberries, pistachios, herbs, and orange zest.', 'Spread mixture onto each crostini.', 'Drizzle with honey if desired.'],
    tips_variation: 'Swap goat cheese for low-sodium ricotta. Use walnuts or pecans instead of pistachios.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'citrus-roasted-beet-arugula-bites': {
    id: 'citrus-roasted-beet-arugula-bites',
    title: 'Citrus-Roasted Beet and Arugula Bites',
    mealType: 'snack',
    servings: 10,
    prepTimeMin: 10,
    cookTimeMin: 30,
    ingredients: ['3 medium red beets', '2 tbsp extra-virgin olive oil', '1 tbsp orange juice', '2 cups baby arugula', '2 ounces low-sodium feta cheese'],
    instructions: ['Roast beets until tender, then cool and dice.', 'Place arugula on crackers or endive leaves.', 'Top with roasted beet, crumbled feta, and chopped walnuts.'],
    tips_variation: 'Substitute golden beets for a milder flavor. Use unsalted pecans or almonds instead of walnuts.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'poached-salmon-cucumber-rounds': {
    id: 'poached-salmon-cucumber-rounds',
    title: 'Poached Salmon Cucumber Rounds with Dill Yogurt',
    mealType: 'snack',
    servings: 10,
    prepTimeMin: 15,
    cookTimeMin: 10,
    ingredients: ['1 large English cucumber', '1/2 pound skinless salmon fillet', '1/2 cup plain low-fat Greek yogurt', '1 tbsp fresh dill, finely chopped'],
    instructions: ['Poach salmon until cooked through, then cool and flake.', 'Slice cucumber into rounds.', 'Mix Greek yogurt with dill, lemon zest, and juice.', 'Top each cucumber round with dill yogurt and flaked salmon.'],
    tips_variation: 'Swap salmon for poached skinless chicken breast. Use low-sodium plain skyr instead of Greek yogurt.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'baked-brie-apple-rosemary': {
    id: 'baked-brie-apple-rosemary',
    title: 'Baked Brie with Apple and Fresh Rosemary',
    mealType: 'snack',
    servings: 8,
    prepTimeMin: 5,
    cookTimeMin: 12,
    ingredients: ['1 (8-ounce) wheel of brie cheese, low-sodium if available', '1 small crisp apple, thinly sliced', '1 tbsp honey', '1 tbsp fresh rosemary, finely chopped'],
    instructions: ['Preheat oven to 375°F.', 'Sauté apple slices until just softened.', 'Top brie with sautéed apples, honey, and rosemary.', 'Bake for 10-12 minutes until soft.', 'Serve with whole-grain crackers.'],
    tips_variation: 'Swap apples for thinly sliced pears. Use unsalted almonds or pumpkin seeds instead of pecans.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'maple-glazed-sweet-potato-rounds': {
    id: 'maple-glazed-sweet-potato-rounds',
    title: 'Maple-Glazed Sweet Potato Rounds with Whipped Feta',
    mealType: 'snack',
    servings: 6,
    prepTimeMin: 10,
    cookTimeMin: 20,
    ingredients: ['2 large sweet potatoes, sliced into rounds', '2 tbsp pure maple syrup', '4 ounces unsalted feta cheese', '1/4 cup plain low-fat Greek yogurt'],
    instructions: ['Roast sweet potato rounds with maple syrup until tender.', 'Whip feta with Greek yogurt and lemon juice until smooth.', 'Top each sweet potato round with whipped feta.'],
    tips_variation: 'Swap feta for unsalted ricotta. Replace maple syrup with honey or agave nectar.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'warm-spinach-artichoke-white-bean-dip': {
    id: 'warm-spinach-artichoke-white-bean-dip',
    title: 'Warm Spinach, Artichoke and White Bean Dip',
    mealType: 'snack',
    servings: 8,
    prepTimeMin: 10,
    cookTimeMin: 20,
    ingredients: ['1 (15-ounce) can no-salt-added cannellini beans', '1 (14-ounce) can no-salt-added artichoke hearts', '4 cups fresh baby spinach', '1/2 cup plain low-fat Greek yogurt'],
    instructions: ['Sauté onion, garlic, and artichoke hearts.', 'Add spinach and cook until wilted.', 'In a food processor, blend cannellini beans and Greek yogurt until smooth.', 'Combine all ingredients, transfer to a baking dish, top with breadcrumbs, and bake until bubbly.'],
    tips_variation: 'Swap cannellini beans for great northern beans. Use low-fat cottage cheese instead of ricotta.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'herb-roasted-mushroom-thyme-tartlets': {
    id: 'herb-roasted-mushroom-thyme-tartlets',
    title: 'Herb-Roasted Mushroom and Thyme Tartlets',
    mealType: 'snack',
    servings: 12,
    prepTimeMin: 15,
    cookTimeMin: 20,
    ingredients: ['1 sheet frozen puff pastry', '10 ounces cremini mushrooms, finely chopped', '1 small shallot, finely minced', '1/2 cup part-skim ricotta cheese', '1 tbsp fresh thyme leaves'],
    instructions: ['Press puff pastry squares into a mini muffin tin.', 'Sauté shallots, garlic, and mushrooms until golden.', 'Combine mushroom mixture with ricotta, herbs, and lemon juice.', 'Fill pastry cups and bake for 18-20 minutes.'],
    tips_variation: 'Use phyllo dough instead of puff pastry for a lighter shell. Substitute baby bella or shiitake mushrooms.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'citrus-marinated-shrimp-skewers': {
    id: 'citrus-marinated-shrimp-skewers',
    title: 'Citrus-Marinated Shrimp Skewers',
    mealType: 'snack',
    servings: 4,
    prepTimeMin: 10,
    cookTimeMin: 6,
    ingredients: ['1 pound large raw shrimp', '2 tbsp orange juice', '1 tbsp lemon juice', '1 tbsp lime juice', '1 red bell pepper, cut into 1-inch pieces'],
    instructions: ['Marinate shrimp in citrus juices, zest, honey, and garlic for 30-45 minutes.', 'Thread shrimp, bell pepper, and red onion onto skewers.', 'Grill for 2-3 minutes per side until shrimp are opaque.'],
    tips_variation: 'Swap shrimp for large sea scallops or chunks of firm white fish. Use pineapple or mango chunks instead of bell pepper.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'pomegranate-walnut-endive-boats': {
    id: 'pomegranate-walnut-endive-boats',
    title: 'Pomegranate Walnut Endive Boats',
    mealType: 'snack',
    servings: 8,
    prepTimeMin: 15,
    cookTimeMin: 0,
    ingredients: ['4 heads Belgian endive', '1 cup fresh pomegranate arils', '1/2 cup raw walnuts, finely chopped', '1/2 cup unsalted ricotta cheese', '2 tbsp plain Greek yogurt'],
    instructions: ['Separate endive leaves.', 'Combine ricotta, yogurt, lemon juice, and honey.', 'Spoon ricotta mixture into endive leaves.', 'Top with toasted walnuts and pomegranate arils.'],
    tips_variation: 'Substitute unsalted goat cheese for ricotta. Use pecans or slivered almonds instead of walnuts.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  'roasted-cauliflower-turmeric-hummus-cups': {
    id: 'roasted-cauliflower-turmeric-hummus-cups',
    title: 'Roasted Cauliflower and Turmeric Hummus Cups',
    mealType: 'snack',
    servings: 12,
    prepTimeMin: 15,
    cookTimeMin: 30,
    ingredients: ['1 medium head cauliflower', '1 tsp ground turmeric', '1 (15-ounce) can no-salt-added chickpeas', '2 tbsp tahini (unsalted)', '24 mini phyllo cups'],
    instructions: ['Roast cauliflower with spices until tender.', 'Blend roasted cauliflower with chickpeas, tahini, and lemon juice until smooth.', 'Spoon the hummus into phyllo cups and serve.'],
    tips_variation: 'Use store-bought low-sodium hummus for a quicker version. Add a sprinkle of paprika on top.',
    source: 'Low-Sodium Christmas Cookbook',
  },
  // --- Dinners ---
  'lemon-herb-cod-asparagus': {
    id: 'lemon-herb-cod-asparagus',
    title: 'Lemon-Herb Roasted Cod with Asparagus',
    mealType: 'dinner',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 15,
    ingredients: ['2 (6-ounce) cod fillets', '1 bunch asparagus, trimmed', '1 tbsp olive oil', '1 lemon, thinly sliced', '1 tsp dried oregano', 'Black pepper to taste'],
    instructions: ['Preheat oven to 400°F (200°C).', 'Toss asparagus with half the olive oil, salt, and pepper on a baking sheet.', 'Place cod fillets on top of asparagus.', 'Drizzle cod with remaining oil, oregano, and top with lemon slices.', 'Bake for 12-15 minutes until fish is opaque and flakes easily.'],
    tips_variation: 'Use salmon or tilapia instead of cod. Add cherry tomatoes or sliced bell peppers to the baking sheet.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'one-pan-chicken-root-veg': {
    id: 'one-pan-chicken-root-veg',
    title: 'One-Pan Chicken with Roasted Root Vegetables',
    mealType: 'dinner',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 30,
    ingredients: ['2 boneless, skinless chicken breasts', '1 sweet potato, cubed', '2 carrots, chopped', '1 red onion, wedged', '1 tbsp olive oil', '1 tsp rosemary'],
    instructions: ['Preheat oven to 400°F (200°C).', 'Toss vegetables with olive oil and rosemary on a baking sheet. Roast for 15 minutes.', 'Add chicken breasts to the pan, stirring vegetables.', 'Roast for another 15-20 minutes until chicken is cooked through and vegetables are tender.'],
    tips_variation: 'Use butternut squash instead of sweet potato. Add Brussels sprouts or broccoli for the last 15 minutes of cooking.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'black-bean-burgers': {
    id: 'black-bean-burgers',
    title: 'Black Bean Burgers on Whole-Wheat Buns',
    mealType: 'dinner',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 10,
    ingredients: ['1 (15-ounce) can no-salt-added black beans, rinsed and mashed', '1/2 cup whole-wheat breadcrumbs', '1/4 cup finely chopped onion', '1 tsp cumin', '2 whole-wheat buns', 'Toppings: lettuce, tomato, avocado'],
    instructions: ['In a bowl, combine mashed black beans, breadcrumbs, onion, and cumin. Form into two patties.', 'Cook patties in a lightly oiled skillet over medium heat for 4-5 minutes per side, until browned.', 'Serve on whole-wheat buns with your favorite toppings.'],
    tips_variation: 'Add corn or chopped bell peppers to the patty mixture. Serve over a salad instead of on a bun.',
    source: 'THE DASH DIET AFTER 50',
  },
  'turkey-pepper-skillet': {
    id: 'turkey-pepper-skillet',
    title: 'Turkey and Bell Pepper Skillet',
    mealType: 'dinner',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 20,
    ingredients: ['1/2 lb ground turkey', '1 red bell pepper, sliced', '1 green bell pepper, sliced', '1/2 onion, sliced', '1 cup no-salt-added tomato sauce', '1/2 cup cooked brown rice'],
    instructions: ['In a large skillet, cook ground turkey until browned. Drain any fat.', 'Add peppers and onion, cooking until tender.', 'Stir in tomato sauce and simmer for 10 minutes.', 'Serve over cooked brown rice.'],
    tips_variation: 'Use ground chicken instead of turkey. Add mushrooms or zucchini with the peppers.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'hearty-lentil-soup': {
    id: 'hearty-lentil-soup',
    title: 'Hearty Vegetable and Lentil Soup',
    mealType: 'dinner',
    servings: 4,
    prepTimeMin: 15,
    cookTimeMin: 30,
    ingredients: ['1 tbsp olive oil', '1 onion, chopped', '2 carrots, chopped', '2 celery stalks, chopped', '1 cup brown or green lentils, rinsed', '4 cups low-sodium vegetable broth', '1 (14.5-ounce) can no-salt-added diced tomatoes'],
    instructions: ['In a large pot, sauté onion, carrots, and celery in olive oil until softened.', 'Add lentils, vegetable broth, and diced tomatoes.', 'Bring to a boil, then reduce heat and simmer for 25-30 minutes, until lentils are tender.', 'Season with black pepper and herbs like thyme or parsley.'],
    tips_variation: 'Add a cup of chopped spinach or kale at the end of cooking. A squeeze of lemon juice brightens the flavor.',
    source: 'THE DASH DIET AFTER 50',
  },
  'sheet-pan-salmon-broccoli': {
    id: 'sheet-pan-salmon-broccoli',
    title: 'Sheet-Pan Salmon and Broccoli',
    mealType: 'dinner',
    servings: 2,
    prepTimeMin: 10,
    cookTimeMin: 15,
    ingredients: ['2 (6-ounce) salmon fillets', '2 cups broccoli florets', '1 tbsp olive oil', '1/2 lemon', '1/4 cup plain low-fat Greek yogurt', '1 tbsp fresh dill, chopped'],
    instructions: ['Preheat oven to 400°F (200°C).', 'Toss broccoli with olive oil and spread on a baking sheet.', 'Place salmon on the sheet, season with pepper and squeeze lemon juice over top.', 'Bake for 12-15 minutes until salmon is cooked through.', 'Mix yogurt and dill for a sauce to serve alongside.'],
    tips_variation: 'Use asparagus or green beans instead of broccoli. Season salmon with smoked paprika for a different flavor.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'stuffed-bell-peppers': {
    id: 'stuffed-bell-peppers',
    title: 'Quinoa and Black Bean Stuffed Bell Peppers',
    mealType: 'dinner',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 25,
    ingredients: ['2 large bell peppers, halved and seeded', '1 cup cooked quinoa', '1/2 cup no-salt-added black beans, rinsed', '1/2 cup no-salt-added corn', '1/4 cup low-sodium salsa', '1/4 cup shredded low-fat cheddar cheese'],
    instructions: ['Preheat oven to 375°F (190°C).', 'In a bowl, mix quinoa, black beans, corn, and salsa.', 'Stuff the bell pepper halves with the mixture.', 'Top with cheese and place in a baking dish with a little water at the bottom.', 'Bake for 20-25 minutes, until peppers are tender.'],
    tips_variation: 'Use brown rice instead of quinoa. Add ground turkey to the filling for extra protein.',
    source: 'THE DASH DIET AFTER 50',
  },
  'chicken-stir-fry': {
    id: 'chicken-stir-fry',
    title: 'Low-Sodium Chicken and Vegetable Stir-fry',
    mealType: 'dinner',
    servings: 2,
    prepTimeMin: 15,
    cookTimeMin: 10,
    ingredients: ['2 boneless, skinless chicken breasts, sliced', '1 cup broccoli florets', '1 carrot, julienned', '1/2 cup snap peas', '1 tbsp low-sodium soy sauce', '1 tsp sesame oil', '1 tsp ginger, minced'],
    instructions: ['In a large skillet or wok, stir-fry chicken until cooked through. Remove from pan.', 'Add vegetables to the pan and stir-fry until crisp-tender.', 'Return chicken to the pan. Add soy sauce, sesame oil, and ginger.', 'Toss to combine and heat through. Serve immediately.'],
    tips_variation: 'Use shrimp or tofu instead of chicken. Add any vegetables you have on hand, like mushrooms, water chestnuts, or bell peppers.',
    source: 'Cookbook DASH Diet for Couples',
  },
  'spaghetti-turkey-meatballs': {
    id: 'spaghetti-turkey-meatballs',
    title: 'Whole-Wheat Spaghetti with Turkey Meatballs',
    mealType: 'dinner',
    servings: 4,
    prepTimeMin: 20,
    cookTimeMin: 25,
    ingredients: ['1 lb ground turkey', '1/2 cup whole-wheat breadcrumbs', '1 egg white, lightly beaten', '1 tsp Italian seasoning', '8 ounces whole-wheat spaghetti', '2 cups no-salt-added marinara sauce'],
    instructions: ['Combine ground turkey, breadcrumbs, egg white, and seasoning. Form into meatballs.', 'Brown meatballs in a skillet, then add marinara sauce. Simmer for 15-20 minutes.', 'Meanwhile, cook spaghetti according to package directions.', 'Serve meatballs and sauce over spaghetti.'],
    tips_variation: 'Add finely chopped onion or spinach to the meatball mixture. Use zucchini noodles instead of spaghetti.',
    source: 'THE DASH DIET AFTER 50',
  },
  'three-bean-chili': {
    id: 'three-bean-chili',
    title: 'Hearty Three-Bean Chili',
    mealType: 'dinner',
    servings: 4,
    prepTimeMin: 10,
    cookTimeMin: 30,
    ingredients: ['1 tbsp olive oil', '1 onion, chopped', '1 (15-ounce) can no-salt-added black beans, rinsed', '1 (15-ounce) can no-salt-added kidney beans, rinsed', '1 (15-ounce) can no-salt-added pinto beans, rinsed', '1 (28-ounce) can no-salt-added crushed tomatoes', '2 tbsp chili powder (salt-free)'],
    instructions: ['In a large pot, sauté onion in olive oil until soft.', 'Add all three kinds of beans, crushed tomatoes, and chili powder.', 'Bring to a simmer and cook for at least 20 minutes to allow flavors to meld.', 'Serve with a dollop of Greek yogurt or a sprinkle of low-fat cheese.'],
    tips_variation: 'Add corn, diced bell peppers, or ground turkey for more substance. Adjust chili powder to your taste.',
    source: 'THE DASH DIET AFTER 50',
  },
};