This XML file does not appear to have any style information associated with it. The document tree is shown below.
<feedback>
<version>1.0</version>
<report_metadata>
<org_name>google.com</org_name>
<email>noreply-dmarc-support@google.com</email>
<extra_contact_info>https://support.google.com/a/answer/2466580</extra_contact_info>
<report_id>18036272301848309875</report_id>
<date_range>
<begin>1764028800</begin>
<end>1764115199</end>
</date_range>
</report_metadata>
<policy_published>
<domain>dashover50.com</domain>
<adkim>r</adkim>
<aspf>r</aspf>
<p>none</p>
<sp>none</sp>
<pct>100</pct>
<np>none</np>
</policy_published>
<record>
<row>
<source_ip>185.236.142.106</source_ip>
<count>1</count>
<policy_evaluated>
<disposition>none</disposition>
<dkim>pass</dkim>
<spf>pass</spf>
</policy_evaluated>
</row>
<identifiers>
<header_from>dashover50.com</header_from>
</identifiers>
<auth_results>
<dkim>
<domain>inbound.systeme.io</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<dkim>
<domain>dashover50.com</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<spf>
<domain>si989887.dashover50.com</domain>
<result>pass</result>
</spf>
</auth_results>
</record>
<record>
<row>
<source_ip>185.236.142.108</source_ip>
<count>2</count>
<policy_evaluated>
<disposition>none</disposition>
<dkim>pass</dkim>
<spf>pass</spf>
</policy_evaluated>
</row>
<identifiers>
<header_from>dashover50.com</header_from>
</identifiers>
<auth_results>
<dkim>
<domain>inbound.systeme.io</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<dkim>
<domain>dashover50.com</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<spf>
<domain>si989887.dashover50.com</domain>
<result>pass</result>
</spf>
</auth_results>
</record>
<record>
<row>
<source_ip>185.236.142.115</source_ip>
<count>1</count>
<policy_evaluated>
<disposition>none</disposition>
<dkim>pass</dkim>
<spf>pass</spf>
</policy_evaluated>
</row>
<identifiers>
<header_from>dashover50.com</header_from>
</identifiers>
<auth_results>
<dkim>
<domain>inbound.systeme.io</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<dkim>
<domain>dashover50.com</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<spf>
<domain>si989887.dashover50.com</domain>
<result>pass</result>
</spf>
</auth_results>
</record>
<record>
<row>
<source_ip>185.236.142.117</source_ip>
<count>2</count>
<policy_evaluated>
<disposition>none</disposition>
<dkim>pass</dkim>
<spf>pass</spf>
</policy_evaluated>
</row>
<identifiers>
<header_from>dashover50.com</header_from>
</identifiers>
<auth_results>
<dkim>
<domain>inbound.systeme.io</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<dkim>
<domain>dashover50.com</domain>
<result>pass</result>
<selector>systemeio1</selector>
</dkim>
<spf>
<domain>si989887.dashover50.com</domain>
<result>pass</result>
</spf>
</auth_results>
</record>
</feedback>
